package com.gd.dataisszmv9.mapper;

import com.gd.dataisszmv9.entity.TBdBranchInfo;

import java.util.List;

public interface TBdBranchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_branch_info
     *
     * @mbggenerated
     */
    int insert(TBdBranchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bd_branch_info
     *
     * @mbggenerated
     */
    int insertSelective(TBdBranchInfo record);

    List<TBdBranchInfo> selectBranchInfos();
}