package com.gd.dataisszmv9.mapper;

import com.gd.dataisszmv9.entity.TImBatch;

public interface TImBatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_im_batch
     *
     * @mbggenerated
     */
    int insert(TImBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_im_batch
     *
     * @mbggenerated
     */
    int insertSelective(TImBatch record);
}