package com.gd.dataisszmv9.mapper;

import com.gd.dataisszmv9.entity.TRmVipSavelist;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public interface TRmVipSavelistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rm_vip_savelist
     *
     * @mbggenerated
     */
    int insert(TRmVipSavelist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rm_vip_savelist
     *
     * @mbggenerated
     */
    int insertSelective(TRmVipSavelist record);

    List<TRmVipSavelist> selectVisaFlows(@Param("flowId") BigDecimal flowId);

    List<TRmVipSavelist> selectCarPayList(@Param("date") Date date);
}